name: CI-CD Example

on:
  workflow_dispatch:
  pull_request:
    # branches: [ main ]
  push:
    # branches: [ main ]
    paths: 
      - .github/workflows/ci-cd.yml
      - src/**

env:
  registry_name: jramgar.azurecr.io
  web_repository_name: eshop-web-demo
  api_repository_name: eshop-api-demo

jobs:
  build-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release


  build-web-image:
    runs-on: ubuntu-latest
    needs: build-ci

    steps:
    - name: Build docker image
      uses: docker/build-push-action@v1.1.1
      with:
        registry: ${{ env.registry_name }}
        username: ${{ secrets.ACR_USER_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        repository: ${{ env.web_repository_name }}
        tags: ${{ github.sha }}
        path: .
        dockerfile: src/Web/Dockerfile
        add_git_labels: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

  build-api-image:
    runs-on: ubuntu-latest
    needs: build-ci

    steps:
    - name: Build docker image
      uses: docker/build-push-action@v1.1.1
      with:
        registry: ${{ env.registry_name }}
        username: ${{ secrets.ACR_USER_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        repository: ${{ env.api_repository_name }}
        tags: ${{ github.sha }}
        path: .
        dockerfile: src/PublicApi/Dockerfile
        add_git_labels: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache      

  deploy:
    needs: 
      - build-web-image
      - build-api-image
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account show
